version: '2'
services:
  build:
    build: .
    image: openswitch/genericx86-64
    command: /bin/true
  fab1:
    image: openswitch/genericx86-64
    container_name: "fab1"
    privileged: true
    ports:
      - "10022:22"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  spine1:
    image: openswitch/genericx86-64
    container_name: "spine1"
    privileged: true
    ports:
      - "11022:22"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
  spine2:
    image: openswitch/genericx86-64
    container_name: "spine2"
    privileged: true
    ports:
      - "12022:22"
    volumes:
      - /tmp:/tmp
      - /dev/log:/dev/log
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - default
    command: /sbin/init
